### ISSUE TITLE
見出しスタイルの変更

### ISSUE THREAD

**Issue by namikuguri** [namikuguri/chroma-hatenablog-theme#5]
heading のとこだけ微妙なフォントサイズになってるので、できれば直したい。h1 ~ h6 の良いスタイルが思いつけば良いが.. 。

現状:

``` css
.entry-content h1 {
  margin: 2.48em 0 0;
  padding-bottom: .21em;
  border-bottom: 1px dashed #E8E8E8;
  font-size: 175%;
  line-height: 1.25;
}

.entry-content h2 {
  margin: 2.48em 0 0;
  padding-bottom: .21em;
  border-bottom: 1px dashed #E8E8E8;
  font-size: 150%;
  line-height: 1.25;
}

.entry-content h3 {
  margin: 2.48em 0 0;
  border-bottom-width: 0;
  font-size: 125%;
  line-height: 1.25;
}

.entry-content h4 {
  margin: 2.48em 0 0;
  font-size: 112.5%;
  line-height: 1.25;
}

.entry-content h5 {
  margin: 2.48em 0 0;
  font-size: inherit;
  line-height: 1.25;
}

.entry-content h6 {
  margin: 2.48em 0 0;
  font-size: 87.5%;
  line-height: 1.25;
}
```
